# k8s/secrets/orders-postgres-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: orders-postgres-secret # Nombre del Secret
type: Opaque # Tipo de Secret para datos arbitrarios
data:
  DB_NAME: b3JkZXJzZGI=
  DB_USERNAME: b3JkZXJzdXNlcg== 
  DB_PASSWORD: dW5hX2NvbnRyYXPxYV9zZWd1cmE= 
