apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-postgres-init-script # Nombre del ConfigMap
data:
  # El contenido del script SQL se define aquí.
  # PostgreSQL ejecutará automáticamente los scripts en /docker-entrypoint-initdb.d/
  init.sql: |
    CREATE TABLE IF NOT EXISTS orders (
        id SERIAL PRIMARY KEY,
        user_id BIGINT NOT NULL,
        items JSONB NOT NULL,
        total_amount DECIMAL(10, 2) NOT NULL,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
