apiVersion: v1
kind: Service
metadata:
  name: orders-postgres-service 
  labels:
    app: orders-postgres
spec:
  selector:
    app: orders-postgres # Coincide con el label del Deployment
  ports:
    - protocol: TCP
      port: 5432 # Puerto del Service
      targetPort: 5432 # Puerto del contenedor al que se dirige el tráfico
  type: ClusterIP # Solo accesible dentro del clúster