apiVersion: v1
kind: Service
metadata:
  name: notifications-service-service # Nombre del Service
  labels:
    app: notifications-service
spec:
  selector:
    app: notifications-service # Coincide con el label del Deployment
  ports:
    - protocol: TCP
      port: 8000 # Puerto del Service en Kubernetes
      targetPort: 8000 # Puerto del contenedor donde escucha FastAPI
  type: ClusterIP # Solo accesible dentro del clúster (no necesita Ingress)
