apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service-deployment
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: ghcr.io/fontsignacio/even-driven-k8s/users-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: users-postgres-secret