apiVersion: v1
kind: Service
metadata:
  name: users-service-service
  labels:
    app: users-service
spec:
  selector:
    app: users-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP # Solo accesible dentro del cluster, expuesto por Ingress
